config/routes.rb
KnowledgeBase::Application.routes.draw do

  resources :users
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :articles
  resources :labels
  resources :categories

  root :to => 'static_pages#home'

  match '/signup',           to:   'users#new'
  match '/signin',           to:   'user_sessions#new'
  match '/signout',          to:   'user_sessions#destroy', via: :delete
  match '/new_article',      to:   'articles#new'
  match '/new_label',        to:   'labels#new'
  match '/create_new_label', to:   'labels#create'
  match 'search',            to:   'static_pages#filter_article'            
  match 'show_label/:id' => 'labels#show', :as => :show_label

end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tag        :string(255)
#

class Article < ActiveRecord::Base
  attr_accessible :content, :title, :tag

  belongs_to :user

  validates :user_id,	presence: true 
  validates :content,	presence: true
  validates :title, 	presence: true
  validates :tag, 		presence: true 
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  color      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  attr_accessible :color, :name

  validates :name, presence: true
  validates :color, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :articles

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true


  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

 include UserSessionsHelper

 before_filter :signed_in_user
 before_filter :correct_user,   only: :destroy

	def new
		@article = current_user.articles.build
		tags = Category.all
		@STATUS = []
		tags.each do |t|
			i = []
			i << t.name
			i << t.id
			@STATUS << i
		end
	end

	def create
		@article = current_user.articles.build(params[:article])
		if @article.save
			flash[:success] = "your article is successfully created!"
      		redirect_to @article
		else
			render 'new'
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def edit
		@article = Article.find(params[:id])
		tags = Category.all
		@STATUS = []
		tags.each do |t|
			i = []
			i << t.name
			i << t.id
			@STATUS << i
		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.update_attributes(params[:article])
			flash[:success] = "Article has been updated successfulyy!"
      		redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		flash[:success] = "your article is successfully deleted!"
    	redirect_to root_path
	end

	private

	def correct_user
      @article = current_user.articles.find_by_id(params[:id])
      redirect_to root_url if @article.nil?
    end
 
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController

	include UserSessionsHelper
	
	before_filter :signed_in_user

	def new
		@label = Category.new
	end

	def create
		@label = Category.new(params[:category])
		if @label.save
			flash[:success] = "New Lable is successfully created!"
      		redirect_to root_path
		else
			render 'new'
		end
	end

	def index
		@label = Category.all
	end

	def show
		@label = Category.find(params[:id])
	end

	def edit
		@label = Category.find(params[:id])
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

include SearchHelper

	def home
		@articles = Article.paginate(page: params[:page])
		@tag = Category.all
	end


	def filter_article
		#@myquery = "SELECT * FROM articles WHERE title LIKE '%%#{params[:q]}%%'"
	#	@articles = ComplexQueries.my_query(@myquery)
		@articles = Article.where("title LIKE ?", "%#{params[:q]}%")
	end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

	include UserSessionsHelper

  	def new
  	end

	def create
		user = User.find_by_email(params[:user_session][:email])
		if user && user.authenticate(params[:user_session][:password])
			sign_in user
			return_back_or user
		else
			flash.now[:error] = "Invalid email/password combination. Please try again."
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

include UserSessionsHelper

before_filter :signed_in_user, only: [:edit, :update]
before_filter :correct_user,   only: [:edit, :update]

	def new
		@user = User.new
	end


	def create
		@user = User.new(params[:user])
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to the Sample App!"
      		redirect_to @user
		else
			render 'new'
		end
	end


	def show
		@user = User.find(params[:id])
		@articles = @user.articles.paginate(page: params[:page])
		@tag = Category.all
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			sign_in @user
			flash[:success] = "Your profile has been updated successfulyy!"
      		redirect_to @user
		else
			render 'edit'
		end
	end


	private

	def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

	def correct_user
		user = User.find(params[:id])
		redirect_to root_url unless current_user?(user)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/search_helper.rb
module SearchHelper
	class ComplexQueries < ActiveRecord::Base
	  def self.my_query q
	    # Notice how you can, and should, still sanitize params here. 
	    self.connection.execute(sanitize_sql([q]))
	  end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper


	def sign_in(user)
		cookies.permanent[:remember_token]=user.remember_token
		self.current_user=user
	end


	def current_user=(user)
		@current_user=user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		self.current_user=nil
		cookies.delete(:remember_token)
	end

	def store_location
		session[:return_to]=request.url
	end

	def return_back_or(default)
		if session[:return_to]
			redirect_to session[:return_to]
			session.delete(:return_to)
		else
			redirect_to default
		end
	end

	def signed_in_user
	    unless signed_in?
	      store_location
	      redirect_to signin_path, notice: "Please sign in." 
	    end
  	end

  	def tag_color tag_id
  		@tag = Category.find_by_id(tag_id)
  		@tag.color
  	end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<li style="border-left-color:<%= tag_color (article.tag)%>">
  <span class="content"><%= link_to article.title, article %></span>
  <span class="content"><%= article.content.html_safe[0..70]%></span>
  <span class="timestamp">
    <br>Posted <%= time_ago_in_words(article.created_at) %> ago by <%=article.user.name%>.
  </span>
</li>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<div class="row">
	<div class="span8 offset2">
		<%= form_for(@article) do |f| %>
		<%= render 'shared/error_messages', object: f.object%>
			<%= f.label :title%>
			<%= f.text_field :title%>

			<%= f.select :tag, @STATUS %>

			<%= f.label :content%>
			<%= f.text_area :content%>
			<br>
			<%= f.submit "Save", class: "btn-large btn-primary" %>
		    <% end %>
	</div>
</div>

<script type="text/javascript">
  $(document).ready(function(){

    $('#article_content').each(function(i, elem) {
      $(elem).wysihtml5();
    });

  })
</script>

app/views/articles/new.html.erb
<h1>New Article</h1>
<div class="row">
	<div class="span8 offset2">
		<%= form_for(@article) do |f| %>
		<%= render 'shared/error_messages', object: f.object%>
			<%= f.label :title%>
			<%= f.text_field :title%>

			<%= f.select :tag, @STATUS %>

			<%= f.label :content%>
			<%= f.text_area :content%>
			<br>
			<%= f.submit "Save", class: "btn-large btn-primary" %>
		    <% end %>
	</div>
</div>

<script type="text/javascript">
  $(document).ready(function(){

    $('#article_content').each(function(i, elem) {
      $(elem).wysihtml5();
    });

  })
</script>

app/views/articles/show.html.erb
<div class ="row">
	<div class="span8 offset2">
		<h2><%= @article.title %></h2>
		<hr>
		<div class="read-article">
		<%= @article.content.html_safe%>
		</div>
		<br>
		<% if current_user?(@article.user) %>
    		<%= link_to "Delete Article", @article, class: "btn-small btn-danger", method: :delete,
                                     confirm: "You sure?",
                                     title: @article.title %>

            <%= link_to "Edit Article", edit_article_path, class: "btn-small btn-danger" %>
  		<% end %>
	</div>
</div>

app/views/labels/edit.html.erb
edit

app/views/labels/index.html.erb
<div class="row">
	<div class="span6 offset3">
		<ol>
			<% @label.each do |l| %>
			<div class="KA-label" style="background-color:<%=l.color%>;"><%= l.name%></div>
			<% end %>
		</ol>
		<hr>
		<%= link_to "Add new Label", new_label_path, class: "btn btn-small btn-primary"%>
	</div>
</div>

app/views/labels/new.html.erb
<h1>New Label</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@label, url: create_new_label_path) do |f| %>
		<%= render 'shared/error_messages', object: f.object%>
			<%= f.label :name%>
			<%= f.text_field :name%>

			<%= f.label :color%>
			<%= f.text_field :color%>
			<br>
			<%= f.submit "Create label", class: "btn btn-primary" %>
		    <% end %>

		    <hr>
		    <div style="font-family:Arial,Helvetica,sans-serif;border:solid 1px #cccccc;position:absolute;width:240px;height:326px;background: #ffffff;-moz-box-shadow:0 0 6px rgba(0,0,0,.25);-webkit-box-shadow: 0 0 6px rgba(0,0,0,.25);box-shadow:0 0 6px rgba(0,0,0,.25);-moz-border-radius: 5px;-webkit-border-radius:5px;border-radius:5px;"><div style="background-color:#2d6ab4;position:absolute;top:0px;left:0px; width:100%; height:22px;text-align:center;padding-top:2px;font-weight:bold;border-top-right-radius:5px;border-top-left-radius:5px;"><a style="text-decoration:none;color:#ffffff;" target="_blank" href="http://www.colorcodehex.com/">HTML Color Picker</a></div><script src="http://widget.colorcodehex.com/color-picker/abcdef.html" type="text/javascript"></script></div>
	</div>
</div>

app/views/labels/show.html.erb
<%= @label.name %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Knowledge-Base by <b>Arun Kaushik</b>
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  
  <div class="navbar-inner">

    <div class="container">
      <%= link_to "Knowldege-Base", root_path, id: "logo"%>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path%></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Sign out", signout_path, method: "delete" %>
                    </li>
                </ul>
            </li>
          <% else %>
                  <li><%= link_to "Sign in", signin_path %></li>
          <%end%>
        </ul>
      </nav>
    </div>

  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KnowledgeBase</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |key, value| %>
        	<div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>


	<%= yield %>
	
	<%= render 'layouts/footer' %>

</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
    <%  if !msg.include? "digest" %>
        <li>* <%= msg %></li>
    <% end %>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/filter_article.html.erb
<% if signed_in? %>
	
	<h1>Articles Found </h1>
	<div class="row">
		<div class="articles-list span8 offset2">
			<div class="control-ribbon">
				<div class="ribbon-element">	<%= link_to "Write new article", new_article_path, class: "btn btn-small btn-primary"%></div>
				<div class="ribbon-element"><%= link_to "Labels", labels_path, class: "btn btn-small btn-primary"%></div>
				<div class="ribbon-element">
					<%= form_tag search_path do %>
						<%= text_field_tag :q, params[:q] %>
						<%= submit_tag "Search", class: "btn btn-small btn-success" %>
	    			<% end %>
	    		</div>
	    	</div>
	    </div>
	</div>
	<div class="row">
		<div class="articles-list span8 offset2">
			<%if @articles.count !=0 %>
		    	<div class="article-list-home">
					<h3>Articles (<%= @articles.count %>)</h3>
				    <ol>
				        <%= render @articles%>
				    </ol>
				</div>
			<%else%>
				<h3>No article found matching to your query</h3>
			<%end%>
		</div>
	</div>
			
<% else %>
<div class ="row">
	<div class="span6 offset3">
		<div class="span6 welcome-box">
			<div class="inner-box"><h2><%= link_to "Sign in", signin_path %></h2></div>
			<div class="inner-box"><h2><%= link_to "Sign up", signup_path %></h2></div>
		</div>
	</div>
</div>
<% end %>

app/views/static_pages/home.html.erb
<% if signed_in? %>
	<h1>List of articles </h1>
	<div class="row">
		<div class="articles-list span8 offset2">
			<div class="control-ribbon">
				<div class="ribbon-element">	<%= link_to "Write new article", new_article_path, class: "btn btn-small btn-primary"%></div>
				<div class="ribbon-element"><%= link_to "Labels", labels_path, class: "btn btn-small btn-primary"%></div>
				<div class="ribbon-element">
					<%= form_tag search_path do %>
						<%= text_field_tag :q, params[:q] %>
						<%= submit_tag "Search", class: "btn btn-small btn-success" %>
	    			<% end %>
	    		</div>
	    	</div>
	    	</div>
	    	</div>
	    	<div class="row">
				<div class="articles-list span8 offset2">
	    			<div class="article-list-home">
				<h3>Articles (<%= @articles.count %>)</h3>
			    <ol>
			        <%= render @articles%>
			    </ol>
			    <%= will_paginate @articles %>
			</div>
		</div>
	</div>
<% else %>
<div class ="row">
	<div class="span6 offset3">
		<h2>Store your Knowldege articles online.</h2>
		<div class="span6 welcome-box">
			<div class="inner-box"><h2><%= link_to "Sign in", signin_path, class: "btn btn-primary btn-large" %></h2></div>
			<div class="inner-box"><h2><%= link_to "Sign up", signup_path, class: "btn btn-primary btn-large"  %></h2></div>
		</div>
	</div>
</div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Sign in</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(:user_session, url: user_sessions_path) do |f|%>

			<%= f.label :email %>
		    <%= f.text_field :email %>

		    <%= f.label :password %>
		    <%= f.password_field :password %>

		    <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
		<% end %>
		 <p>New user? <%= link_to "Sign up now!", signup_path %></p>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Signup</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages', object: f.object%>
			<%= f.label :name%>
			<%= f.text_field :name%>

			<%= f.label :email%>
			<%= f.text_field :email%>

			<%= f.label :password%>
			<%= f.password_field :password%>

			<%= f.label :password_confirmation, "Confirm password"%>
			<%= f.password_field :password_confirmation%>
			<br>
			<%= f.submit "Create my account", class: "btn btn-primary" %>
		    <% end %>
	</div>
</div>

app/views/users/show.html.erb
<h1><%= current_user.name %></h1>
<div class="row">
	<div class="articles-list span8 offset2 ">
	    <% if @user.articles.any? %>
	      <h3>Articles (<%= @user.articles.count %>)</h3>
	      <ol>
	        <%= render @articles%>
	      </ol>
	      <%= will_paginate @articles %>
	    <% end %>
	</div>
</div>